import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import PageTransitionEffect from '../system/PageTransitionEffect'
import ContextProvider from '@/system/ContextProvider'
import Navigation from '@/components/Navigation'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className='p-12 lg:p-24'>
      <body className={inter.className}>
        <ContextProvider>
          <Navigation />
          <PageTransitionEffect>{children}</PageTransitionEffect>
        </ContextProvider>
      </body>
    </html>
  )
}
